import { prisma } from "@/app/lib/prisma";
import { getCrmOwnerUserId } from "@/app/lib/crm-owner"; 
export const dynamic = "force-dynamic";
function formatDate(date: Date | null) { if (!date) return "—"; return new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium" }).format(date); }
export default async function CrmDashboardPage() {
  const userId = await getCrmOwnerUserId();
  const [contactsCount, companiesCount, opportunitiesCount, tasksToDoCount, recentOpportunities, urgentTasks] = await Promise.all([
    prisma.contact.count({ where: { userId } }),
    prisma.crmCompany.count({ where: { userId } }),
    prisma.crmOpportunity.count({ where: { userId } }),
    prisma.crmTask.count({ where: { userId, status: { in: ["TODO", "IN_PROGRESS"] } } }),
    prisma.crmOpportunity.findMany({ where: { userId }, take: 6, orderBy: { createdAt: "desc" }, include: { contact: true, company: true, product: true } }),
    prisma.crmTask.findMany({ where: { userId, status: { in: ["TODO", "IN_PROGRESS"] } }, take: 6, orderBy: { dueDate: "asc" }, include: { contact: true, opportunity: true } }),
  ]);
  return <><header className="crm-page-header"><div><p className="crm-eyebrow">Vue generale</p><h1 className="crm-title">Dashboard CRM</h1><p className="crm-subtitle">Suivi des contacts, opportunites commerciales, relances et demandes issues du site, des campagnes et des reseaux sociaux.</p></div></header><section className="crm-stats-grid"><div className="crm-card crm-stat-card"><p className="crm-stat-label">Contacts</p><p className="crm-stat-value">{contactsCount}</p></div><div className="crm-card crm-stat-card"><p className="crm-stat-label">Entreprises</p><p className="crm-stat-value">{companiesCount}</p></div><div className="crm-card crm-stat-card"><p className="crm-stat-label">Opportunites</p><p className="crm-stat-value">{opportunitiesCount}</p></div><div className="crm-card crm-stat-card"><p className="crm-stat-label">Relances a faire</p><p className="crm-stat-value">{tasksToDoCount}</p></div></section><section className="crm-grid"><div className="crm-card crm-section"><h2 className="crm-section-title">Opportunites recentes</h2>{recentOpportunities.length === 0 ? <div className="crm-empty">Aucune opportunite pour le moment.</div> : <table className="crm-table"><thead><tr><th>Titre</th><th>Produit</th><th>Contact</th><th>Etape</th><th>Source</th></tr></thead><tbody>{recentOpportunities.map((opportunity) => <tr key={opportunity.id}><td><span className="crm-name">{opportunity.title}</span></td><td>{opportunity.product?.name || "—"}</td><td>{opportunity.contact?.firstName || opportunity.contact?.lastName ? `${opportunity.contact?.firstName || ""} ${opportunity.contact?.lastName || ""}` : opportunity.contact?.email || "—"}</td><td><span className="crm-badge">{opportunity.stage}</span></td><td>{opportunity.source}</td></tr>)}</tbody></table>}</div><div className="crm-card crm-section"><h2 className="crm-section-title">Relances prioritaires</h2>{urgentTasks.length === 0 ? <div className="crm-empty">Aucune relance en attente.</div> : <table className="crm-table"><thead><tr><th>Tache</th><th>Contact</th><th>Echeance</th><th>Priorite</th></tr></thead><tbody>{urgentTasks.map((task) => <tr key={task.id}><td><span className="crm-name">{task.title}</span></td><td>{task.contact?.email || "—"}</td><td>{formatDate(task.dueDate)}</td><td><span className="crm-badge crm-badge-orange">{task.priority}</span></td></tr>)}</tbody></table>}</div></section></>;
}
