import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// ─── Références MD2I à créer ─────────────────────────────────────────────────
const REFERENCES = [
  // France - Projet 1
  {
    id: "ref_fr_001",
    country: "France",
    code: "fr",
    lat: 46.603,
    lng: 1.888,
    title: "MD2I — Transformation digitale Groupe La Poste",
    slug: "transformation-digitale-groupe-la-poste",
    excerpt: "Refonte complète des services numériques et accompagnement des équipes sur 3 ans.",
    image: "https://picsum.photos/id/20/800/500",
    details: "Mission complète de conseil UX/UI, conduite du changement et formation de 120 équipes métiers. Refonte de 14 portails internes, migration vers une architecture microservices, et déploiement d'une plateforme omnicanale. Résultat : +42% de satisfaction client, réduction de 30% du temps de traitement des demandes.",
    date: "2023",
    client: "Groupe La Poste",
    category: "Transformation digitale",
    tags: ["UX/UI", "Microservices", "Omnicanal"],
    impact: "+42% satisfaction client",
    technologies: ["React", "Node.js", "Kafka", "Docker"],
    team: "12 consultants",
    duration: "18 mois",
    budget: "2.4M€",
    status: "PUBLISHED",
    publishedAt: new Date(),
  },
  // France - Projet 2
  {
    id: "ref_fr_002",
    country: "France",
    code: "fr",
    lat: 46.85,
    lng: 2.35,
    title: "MD2I — IA prédictive pour SNCF Réseau",
    slug: "ia-predictive-sncf-reseau",
    excerpt: "Maintenance prédictive des infrastructures ferroviaires par deep learning.",
    image: "https://picsum.photos/id/13/800/500",
    details: "Déploiement d'une solution de maintenance prédictive sur 5000 km de voies ferrées. Analyse en temps réel de 100 000 capteurs IoT, réduction des incidents de 67%, économie de 120M€ sur 5 ans.",
    date: "2024",
    client: "SNCF Réseau",
    category: "IA & Data Science",
    tags: ["Deep Learning", "IoT", "Maintenance prédictive"],
    impact: "67% réduction des incidents",
    technologies: ["TensorFlow", "Kafka", "InfluxDB", "Grafana"],
    team: "8 data scientists",
    duration: "24 mois",
    budget: "3.1M€",
    status: "PUBLISHED",
    publishedAt: new Date(),
  },
  // France - Projet 3
  {
    id: "ref_fr_003",
    country: "France",
    code: "fr",
    lat: 45.76,
    lng: 4.84,
    title: "MD2I — Smart Building pour Lyon Métropole",
    slug: "smart-building-lyon-metropole",
    excerpt: "Gestion intelligente des consommations énergétiques des bâtiments publics.",
    image: "https://picsum.photos/id/153/800/500",
    details: "Déploiement d'une plateforme de smart building pour 340 bâtiments publics. Optimisation énergétique par IA, réduction de 45% des consommations, ROI en 18 mois.",
    date: "2023",
    client: "Métropole de Lyon",
    category: "Smart Building",
    tags: ["IoT", "Efficacité énergétique", "BIM"],
    impact: "-45% consommation énergétique",
    technologies: ["LoRaWAN", "MQTT", "TimescaleDB"],
    team: "6 ingénieurs",
    duration: "14 mois",
    budget: "1.8M€",
    status: "PUBLISHED",
    publishedAt: new Date(),
  },
  // Allemagne - Projet 1
  {
    id: "ref_de_001",
    country: "Allemagne",
    code: "de",
    lat: 51.165,
    lng: 10.451,
    title: "MD2I — Industrie 4.0 & jumeaux numériques Siemens",
    slug: "industrie-40-jumeaux-numeriques-siemens",
    excerpt: "Conception d'une plateforme de simulation industrielle en temps réel pour 8 usines.",
    image: "https://picsum.photos/id/48/800/500",
    details: "Déploiement d'une infrastructure IoT connectant 2 400 capteurs dans 8 sites de production. Création de jumeaux numériques permettant la simulation de scénarios de production et la maintenance prédictive. L'IA embarquée réduit les arrêts non planifiés de 67%.",
    date: "2023",
    client: "Siemens AG",
    category: "Industrie 4.0",
    tags: ["Digital Twin", "IoT", "IA embarquée"],
    impact: "-67% arrêts non planifiés",
    technologies: ["AWS IoT", "Unity", "PyTorch"],
    team: "15 experts",
    duration: "20 mois",
    budget: "4.2M€",
    status: "PUBLISHED",
    publishedAt: new Date(),
  },
  // Allemagne - Projet 2
  {
    id: "ref_de_002",
    country: "Allemagne",
    code: "de",
    lat: 50.11,
    lng: 8.68,
    title: "MD2I — Cybersécurité automobile pour Mercedes-Benz",
    slug: "cybersecurite-automobile-mercedes-benz",
    excerpt: "Plateforme de détection d'intrusion pour véhicules connectés.",
    image: "https://picsum.photos/id/91/800/500",
    details: "Développement d'un IDS (Intrusion Detection System) pour les futures générations de véhicules. Analyse comportementale embarquée, protection en temps réel contre les cyberattaques. Certification ISO 21434 obtenue.",
    date: "2024",
    client: "Mercedes-Benz AG",
    category: "Cybersécurité",
    tags: ["Automotive", "IDS", "Sécurité embarquée"],
    impact: "100% des flottes protégées",
    technologies: ["Rust", "TensorFlow Lite", "CAN bus"],
    team: "10 ingénieurs sécurité",
    duration: "16 mois",
    budget: "2.9M€",
    status: "PUBLISHED",
    publishedAt: new Date(),
  },
  // États-Unis - Projet 1
  {
    id: "ref_us_001",
    country: "États-Unis",
    code: "us",
    lat: 37.09,
    lng: -95.712,
    title: "MD2I — IA médicale & diagnostic prédictif Boston Medical",
    slug: "ia-medicale-diagnostic-predictif-boston-medical",
    excerpt: "Déploiement d'un système de diagnostic assisté par IA dans 12 hôpitaux.",
    image: "https://picsum.photos/id/26/800/500",
    details: "Développement d'une IA capable d'analyser 50 000 images radiologiques par jour. Précision de 97,3% sur la détection précoce de tumeurs pulmonaires. Déploiement dans 12 hôpitaux, formation de 450 radiologues.",
    date: "2024",
    client: "Boston Medical Center",
    category: "HealthTech & IA",
    tags: ["Medical Imaging", "Deep Learning", "Diagnostic"],
    impact: "97.3% précision diagnostic",
    technologies: ["PyTorch", "MONAI", "DICOM", "Kubernetes"],
    team: "14 chercheurs",
    duration: "22 mois",
    budget: "5.5M$",
    status: "PUBLISHED",
    publishedAt: new Date(),
  },
  // États-Unis - Projet 2
  {
    id: "ref_us_002",
    country: "États-Unis",
    code: "us",
    lat: 40.7128,
    lng: -74.006,
    title: "MD2I — Optimisation financière pour JPMorgan Chase",
    slug: "optimisation-financiere-jpmorgan-chase",
    excerpt: "Algorithmes de trading haute fréquence et gestion des risques.",
    image: "https://picsum.photos/id/77/800/500",
    details: "Développement de modèles de prédiction pour le trading algorithmique. Latence inférieure à 1ms, détection d'anomalies en temps réel, conformité SEC/FINRA. Performance supérieure de 34% aux benchmarks du marché.",
    date: "2023",
    client: "JPMorgan Chase",
    category: "Fintech",
    tags: ["HFT", "Risk Management", "ML"],
    impact: "+34% performance",
    technologies: ["C++", "Python", "Apache Flink"],
    team: "9 quants",
    duration: "15 mois",
    budget: "3.8M$",
    status: "PUBLISHED",
    publishedAt: new Date(),
  },
  // États-Unis - Projet 3
  {
    id: "ref_us_003",
    country: "États-Unis",
    code: "us",
    lat: 37.7749,
    lng: -122.4194,
    title: "MD2I — Cloud natif pour Netflix",
    slug: "cloud-natif-netflix",
    excerpt: "Migration complète vers une architecture serverless multicloud.",
    image: "https://picsum.photos/id/42/800/500",
    details: "Migration de 200 microservices vers serverless. Réduction des coûts de 42%, amélioration de la scalabilité (10M à 200M utilisateurs). Disponibilité 99.999% maintenue.",
    date: "2023",
    client: "Netflix",
    category: "Cloud & DevOps",
    tags: ["Serverless", "Multicloud", "Microservices"],
    impact: "-42% coûts infrastructure",
    technologies: ["AWS Lambda", "Terraform", "Kubernetes"],
    team: "20 DevOps",
    duration: "18 mois",
    budget: "6.2M$",
    status: "PUBLISHED",
    publishedAt: new Date(),
  },
  // Espagne
  {
    id: "ref_es_001",
    country: "Espagne",
    code: "es",
    lat: 40.416,
    lng: -3.703,
    title: "MD2I — Smart City Barcelone 2030",
    slug: "smart-city-barcelone-2030",
    excerpt: "Déploiement d'une plateforme urbaine intelligente pour 1,6M d'habitants.",
    image: "https://picsum.photos/id/59/800/500",
    details: "Conception d'une plateforme de gestion urbaine intégrée couvrant mobilité, énergie, déchets et sécurité. Intégration de 180 000 capteurs. Réduction de 25% de la consommation énergétique.",
    date: "2022",
    client: "Mairie de Barcelone",
    category: "Smart City",
    tags: ["IoT", "Urban Data", "Mobilité"],
    impact: "-25% consommation énergétique",
    technologies: ["FIWARE", "LoRaWAN", "Kafka"],
    team: "25 experts",
    duration: "30 mois",
    budget: "7.5M€",
    status: "PUBLISHED",
    publishedAt: new Date(),
  },
  // Italie
  {
    id: "ref_it_001",
    country: "Italie",
    code: "it",
    lat: 41.902,
    lng: 12.496,
    title: "MD2I — Luxe digital Ferragamo",
    slug: "luxe-digital-ferragamo",
    excerpt: "Stratégie digitale omnicanale pour la maison de couture florentine.",
    image: "https://picsum.photos/id/36/800/500",
    details: "Refonte de l'expérience digitale : e-commerce, app mobile, réalité virtuelle. IA de recommandation personnalisée. Résultats : +89% conversion e-commerce, +35% panier moyen.",
    date: "2022",
    client: "Salvatore Ferragamo",
    category: "Luxe & Digital",
    tags: ["E-commerce", "VR/AR", "Personalization"],
    impact: "+89% conversion",
    technologies: ["Vue.js", "Strapi", "Algolia"],
    team: "8 développeurs",
    duration: "12 mois",
    budget: "1.5M€",
    status: "PUBLISHED",
    publishedAt: new Date(),
  },
  // Royaume-Uni
  {
    id: "ref_gb_001",
    country: "Royaume-Uni",
    code: "gb",
    lat: 51.507,
    lng: -0.127,
    title: "MD2I — Fintech Revolut",
    slug: "fintech-revolut",
    excerpt: "Audit et refonte de l'architecture pour la licence bancaire européenne.",
    image: "https://picsum.photos/id/180/800/500",
    details: "Mise en conformité PSD2/RGPD, détection de fraude par ML, refonte sécurité. Accompagnement de 450 ingénieurs.",
    date: "2023",
    client: "Revolut",
    category: "Fintech",
    tags: ["Conformité", "Fraud Detection", "Security"],
    impact: "Licence bancaire obtenue",
    technologies: ["Go", "Kafka", "Datadog"],
    team: "18 consultants",
    duration: "14 mois",
    budget: "4.2M£",
    status: "PUBLISHED",
    publishedAt: new Date(),
  },
  // Japon
  {
    id: "ref_jp_001",
    country: "Japon",
    code: "jp",
    lat: 35.685,
    lng: 139.751,
    title: "MD2I — Robotique collaborative Toyota",
    slug: "robotique-collaborative-toyota",
    excerpt: "Intégration de robots collaboratifs dans les usines de Nagoya.",
    image: "https://picsum.photos/id/160/800/500",
    details: "Intégration de 340 cobots dans 6 lignes d'assemblage, vision par ordinateur pour contrôle qualité. Gain de productivité de 38%.",
    date: "2023",
    client: "Toyota",
    category: "Robotique",
    tags: ["Cobots", "Computer Vision", "Industry 4.0"],
    impact: "+38% productivité",
    technologies: ["ROS2", "OpenCV", "NVIDIA Jetson"],
    team: "12 roboticiens",
    duration: "20 mois",
    budget: "5.8M$",
    status: "PUBLISHED",
    publishedAt: new Date(),
  },
  // Chine
  {
    id: "ref_cn_001",
    country: "Chine",
    code: "cn",
    lat: 30.572,
    lng: 104.066,
    title: "MD2I — Supply Chain Alibaba",
    slug: "supply-chain-alibaba",
    excerpt: "Optimisation logistique par reinforcement learning.",
    image: "https://picsum.photos/id/96/800/500",
    details: "Système d'optimisation prédisant la demande à J+7 avec 94% précision, optimisation des routes. Économie de 180M$ annuels.",
    date: "2024",
    client: "Alibaba",
    category: "Supply Chain",
    tags: ["RL", "Demand Forecasting", "Route Optimization"],
    impact: "-180M$ économies",
    technologies: ["Ray", "PyTorch", "Redis"],
    team: "16 data scientists",
    duration: "24 mois",
    budget: "9.5M$",
    status: "PUBLISHED",
    publishedAt: new Date(),
  },
  // Brésil
  {
    id: "ref_br_001",
    country: "Brésil",
    code: "br",
    lat: -14.235,
    lng: -51.925,
    title: "MD2I — Logistique dernier kilomètre Mercado Livre",
    slug: "logistique-dernier-kilometre-mercado-livre",
    excerpt: "Plateforme de livraison pour 5 500 municipalités.",
    image: "https://picsum.photos/id/117/800/500",
    details: "Crowdsourcing + optimisation algorithmique. App mobile pour 80 000 livreurs. Réduction de 45% du délai de livraison.",
    date: "2022",
    client: "Mercado Livre",
    category: "Logistique",
    tags: ["Last Mile", "Crowdsourcing", "Routing"],
    impact: "-45% délais livraison",
    technologies: ["React Native", "GraphQL", "PostGIS"],
    team: "22 développeurs",
    duration: "16 mois",
    budget: "3.2M$",
    status: "PUBLISHED",
    publishedAt: new Date(),
  },
  // Afrique du Sud - Projet 1
  {
    id: "ref_za_001",
    country: "Afrique du Sud",
    code: "za",
    lat: -30.559,
    lng: 22.937,
    title: "MD2I — Réseau solaire Eskom",
    slug: "reseau-solaire-eskom",
    excerpt: "Plateforme de gestion pour 4 GW d'énergie solaire.",
    image: "https://picsum.photos/id/145/800/500",
    details: "SCADA nouvelle génération pour 47 centrales solaires, prévision de production par IA météo. Gestion de l'intermittence par algorithmes de stockage.",
    date: "2024",
    client: "Eskom Holdings",
    category: "Énergie",
    tags: ["Renewable Energy", "SCADA", "Forecasting"],
    impact: "+28% production solaire",
    technologies: ["Python", "InfluxDB", "Grafana"],
    team: "11 ingénieurs",
    duration: "28 mois",
    budget: "6.5M$",
    status: "PUBLISHED",
    publishedAt: new Date(),
  },
  // Afrique du Sud - Projet 2
  {
    id: "ref_za_002",
    country: "Afrique du Sud",
    code: "za",
    lat: -30.52,
    lng: 22.97,
    title: "MD2I — Fintech inclusive pour TymeBank",
    slug: "fintech-inclusive-tymebank",
    excerpt: "Plateforme bancaire digitale pour les populations non bancarisées.",
    image: "https://picsum.photos/id/99/800/500",
    details: "Déploiement d'une solution bancaire 100% mobile pour 5 millions d'utilisateurs en zone rurale. Architecture cloud-native, onboarding biométrique, micro-crédit algorithmique. Croissance de 200% du portefeuille client en 18 mois.",
    date: "2023",
    client: "TymeBank",
    category: "Fintech inclusive",
    tags: ["Digital Banking", "Financial Inclusion", "Biometrics"],
    impact: "5M utilisateurs actifs",
    technologies: ["React Native", "Node.js", "MongoDB", "AWS"],
    team: "14 experts fintech",
    duration: "15 mois",
    budget: "2.8M$",
    status: "PUBLISHED",
    publishedAt: new Date(),
  },
]

async function main() {
  console.log('🌱 Démarrage du seeder pour les références MD2I…\n')

  let created = 0
  let updated = 0

  for (const ref of REFERENCES) {
    const existing = await prisma.reference.findUnique({
      where: { slug: ref.slug },
    })

    if (existing) {
      await prisma.reference.update({
        where: { slug: ref.slug },
        data: ref,
      })
      updated++
      console.log(`🔄 Référence mise à jour : ${ref.title}`)
    } else {
      await prisma.reference.create({
        data: ref,
      })
      created++
      console.log(`✅ Référence créée : ${ref.title}`)
    }
  }

  console.log('\n────────────────────────────────────')
  console.log('🎉 Seeder des références MD2I terminé avec succès !')
  console.log('────────────────────────────────────')
  console.log(`📚 Nombre total de références : ${REFERENCES.length}`)
  console.log(`✨ Créées : ${created}`)
  console.log(`🔄 Mises à jour : ${updated}`)
  console.log('────────────────────────────────────\n')
}

main()
  .catch(e => {
    console.error('❌ Erreur seeder :', e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())