// Config StyleManager partagée entre l'éditeur d'articles (GrapesEditor) et l'éditeur produits (ProductStudio).
// Unique surface d'édition de style : le formulaire "quick style" redondant a été retiré des deux éditeurs.
export const STYLE_MANAGER_SECTORS = [
  {
    id: "typography",
    name: "Texte",
    open: true,
    properties: [
      {
        name: "Taille police",
        property: "font-size",
        type: "integer" as any,
        units: ["px", "em", "rem", "%", "vw"],
        unit: "px",
        min: 1,
        max: 200,
      },
      {
        name: "Graisse",
        property: "font-weight",
        type: "select" as any,
        options: [
          { id: "300", label: "Light 300" },
          { id: "400", label: "Normal 400" },
          { id: "500", label: "Medium 500" },
          { id: "600", label: "Semibold 600" },
          { id: "700", label: "Bold 700" },
          { id: "800", label: "Extrabold 800" },
          { id: "900", label: "Black 900" },
        ],
      },
      {
        name: "Hauteur de ligne",
        property: "line-height",
        type: "integer" as any,
        units: ["", "px", "em"],
        unit: "",
        min: 1,
        max: 5,
        step: 0.05,
      },
      {
        name: "Espacement lettres",
        property: "letter-spacing",
        type: "integer" as any,
        units: ["px", "em"],
        unit: "px",
        min: -10,
        max: 50,
      },
      {
        name: "Couleur texte",
        property: "color",
        type: "color" as any,
      },
      {
        name: "Alignement",
        property: "text-align",
        type: "radio" as any,
        options: [
          { id: "left", label: "←" },
          { id: "center", label: "↔" },
          { id: "right", label: "→" },
          { id: "justify", label: "≡" },
        ],
      },
      {
        name: "Décoration",
        property: "text-decoration",
        type: "select" as any,
        options: [
          { id: "none", label: "Aucune" },
          { id: "underline", label: "Souligné" },
          { id: "line-through", label: "Barré" },
          { id: "overline", label: "Au-dessus" },
        ],
      },
      {
        name: "Transformation",
        property: "text-transform",
        type: "select" as any,
        options: [
          { id: "none", label: "Aucune" },
          { id: "uppercase", label: "MAJUSCULES" },
          { id: "lowercase", label: "minuscules" },
          { id: "capitalize", label: "Capitalize" },
        ],
      },
      {
        name: "Famille police",
        property: "font-family",
        type: "select" as any,
        options: [
          { id: "Inter, Arial, sans-serif", label: "Inter" },
          { id: "Arial, Helvetica, sans-serif", label: "Arial" },
          { id: "Georgia, serif", label: "Georgia" },
          { id: "system-ui, sans-serif", label: "System UI" },
          { id: "ui-monospace, monospace", label: "Monospace" },
        ],
      },
    ],
  },
  {
    id: "background",
    name: "Arrière-plan",
    open: false,
    properties: [
      {
        name: "Couleur de fond",
        property: "background-color",
        type: "color" as any,
      },
      {
        name: "Image de fond",
        property: "background-image",
        type: "base" as any,
      },
      {
        name: "Taille fond",
        property: "background-size",
        type: "select" as any,
        options: [
          { id: "auto", label: "Auto" },
          { id: "cover", label: "Cover" },
          { id: "contain", label: "Contain" },
        ],
      },
      {
        name: "Position fond",
        property: "background-position",
        type: "select" as any,
        options: [
          { id: "center", label: "Centre" },
          { id: "top", label: "Haut" },
          { id: "bottom", label: "Bas" },
          { id: "left", label: "Gauche" },
          { id: "right", label: "Droite" },
        ],
      },
      {
        name: "Répétition fond",
        property: "background-repeat",
        type: "select" as any,
        options: [
          { id: "no-repeat", label: "Aucune" },
          { id: "repeat", label: "Répéter" },
          { id: "repeat-x", label: "Horizontal" },
          { id: "repeat-y", label: "Vertical" },
        ],
      },
    ],
  },
  {
    id: "border",
    name: "Bordure & coins",
    open: false,
    properties: [
      {
        name: "Couleur bordure",
        property: "border-color",
        type: "color" as any,
      },
      {
        name: "Épaisseur bordure",
        property: "border-width",
        type: "integer" as any,
        units: ["px"],
        unit: "px",
        min: 0,
        max: 30,
      },
      {
        name: "Style bordure",
        property: "border-style",
        type: "select" as any,
        options: [
          { id: "none", label: "Aucune" },
          { id: "solid", label: "Solide" },
          { id: "dashed", label: "Tirets" },
          { id: "dotted", label: "Points" },
          { id: "double", label: "Double" },
        ],
      },
      {
        name: "Rayon global",
        property: "border-radius",
        type: "integer" as any,
        units: ["px", "%"],
        unit: "px",
        min: 0,
        max: 999,
      },
      {
        name: "Rayon haut-gauche",
        property: "border-top-left-radius",
        type: "integer" as any,
        units: ["px", "%"],
        unit: "px",
        min: 0,
        max: 999,
      },
      {
        name: "Rayon haut-droit",
        property: "border-top-right-radius",
        type: "integer" as any,
        units: ["px", "%"],
        unit: "px",
        min: 0,
        max: 999,
      },
      {
        name: "Rayon bas-gauche",
        property: "border-bottom-left-radius",
        type: "integer" as any,
        units: ["px", "%"],
        unit: "px",
        min: 0,
        max: 999,
      },
      {
        name: "Rayon bas-droit",
        property: "border-bottom-right-radius",
        type: "integer" as any,
        units: ["px", "%"],
        unit: "px",
        min: 0,
        max: 999,
      },
      {
        name: "Outline",
        property: "outline",
        type: "base" as any,
      },
    ],
  },
  {
    id: "dimensions",
    name: "Dimensions",
    open: false,
    properties: [
      {
        name: "Largeur",
        property: "width",
        type: "integer" as any,
        units: ["px", "%", "vw", "em", "rem", "auto"],
        unit: "px",
        min: 0,
        max: 5000,
      },
      {
        name: "Hauteur",
        property: "height",
        type: "integer" as any,
        units: ["px", "%", "vh", "em", "rem", "auto"],
        unit: "px",
        min: 0,
        max: 5000,
      },
      {
        name: "Larg. min",
        property: "min-width",
        type: "integer" as any,
        units: ["px", "%", "vw", "em", "rem"],
        unit: "px",
        min: 0,
        max: 5000,
      },
      {
        name: "Haut. min",
        property: "min-height",
        type: "integer" as any,
        units: ["px", "%", "vh", "em", "rem"],
        unit: "px",
        min: 0,
        max: 5000,
      },
      {
        name: "Larg. max",
        property: "max-width",
        type: "integer" as any,
        units: ["px", "%", "vw", "em", "rem"],
        unit: "px",
        min: 0,
        max: 5000,
      },
      {
        name: "Haut. max",
        property: "max-height",
        type: "integer" as any,
        units: ["px", "%", "vh", "em", "rem"],
        unit: "px",
        min: 0,
        max: 5000,
      },
    ],
  },
  {
    id: "spacing",
    name: "Espacement (Margin / Padding)",
    open: false,
    properties: [
      {
        name: "Margin haut",
        property: "margin-top",
        type: "integer" as any,
        units: ["px", "%", "em", "rem", "auto"],
        unit: "px",
        min: -500,
        max: 500,
      },
      {
        name: "Margin droite",
        property: "margin-right",
        type: "integer" as any,
        units: ["px", "%", "em", "rem", "auto"],
        unit: "px",
        min: -500,
        max: 500,
      },
      {
        name: "Margin bas",
        property: "margin-bottom",
        type: "integer" as any,
        units: ["px", "%", "em", "rem", "auto"],
        unit: "px",
        min: -500,
        max: 500,
      },
      {
        name: "Margin gauche",
        property: "margin-left",
        type: "integer" as any,
        units: ["px", "%", "em", "rem", "auto"],
        unit: "px",
        min: -500,
        max: 500,
      },
      {
        name: "Padding haut",
        property: "padding-top",
        type: "integer" as any,
        units: ["px", "%", "em", "rem"],
        unit: "px",
        min: 0,
        max: 500,
      },
      {
        name: "Padding droite",
        property: "padding-right",
        type: "integer" as any,
        units: ["px", "%", "em", "rem"],
        unit: "px",
        min: 0,
        max: 500,
      },
      {
        name: "Padding bas",
        property: "padding-bottom",
        type: "integer" as any,
        units: ["px", "%", "em", "rem"],
        unit: "px",
        min: 0,
        max: 500,
      },
      {
        name: "Padding gauche",
        property: "padding-left",
        type: "integer" as any,
        units: ["px", "%", "em", "rem"],
        unit: "px",
        min: 0,
        max: 500,
      },
    ],
  },
  {
    id: "layout",
    name: "Disposition",
    open: false,
    properties: [
      {
        name: "Display",
        property: "display",
        type: "select" as any,
        options: [
          { id: "block", label: "Block" },
          { id: "inline-block", label: "Inline-block" },
          { id: "inline", label: "Inline" },
          { id: "flex", label: "Flex" },
          { id: "inline-flex", label: "Inline-flex" },
          { id: "grid", label: "Grid" },
          { id: "none", label: "Masqué (none)" },
        ],
      },
      {
        name: "Position",
        property: "position",
        type: "select" as any,
        options: [
          { id: "static", label: "Static" },
          { id: "relative", label: "Relative" },
          { id: "absolute", label: "Absolute" },
          { id: "fixed", label: "Fixed" },
          { id: "sticky", label: "Sticky" },
        ],
      },
      {
        name: "Top",
        property: "top",
        type: "integer" as any,
        units: ["px", "%", "em"],
        unit: "px",
      },
      {
        name: "Right",
        property: "right",
        type: "integer" as any,
        units: ["px", "%", "em"],
        unit: "px",
      },
      {
        name: "Bottom",
        property: "bottom",
        type: "integer" as any,
        units: ["px", "%", "em"],
        unit: "px",
      },
      {
        name: "Left",
        property: "left",
        type: "integer" as any,
        units: ["px", "%", "em"],
        unit: "px",
      },
      {
        name: "Z-index",
        property: "z-index",
        type: "integer" as any,
        units: [""],
        unit: "",
        min: -999,
        max: 9999,
      },
      {
        name: "Overflow",
        property: "overflow",
        type: "select" as any,
        options: [
          { id: "visible", label: "Visible" },
          { id: "hidden", label: "Caché" },
          { id: "scroll", label: "Scroll" },
          { id: "auto", label: "Auto" },
        ],
      },
    ],
  },
  {
    id: "flexgrid",
    name: "Flex / Grid",
    open: false,
    properties: [
      {
        name: "Direction flex",
        property: "flex-direction",
        type: "select" as any,
        options: [
          { id: "row", label: "Row →" },
          { id: "row-reverse", label: "Row ←" },
          { id: "column", label: "Column ↓" },
          { id: "column-reverse", label: "Column ↑" },
        ],
      },
      {
        name: "Flex wrap",
        property: "flex-wrap",
        type: "select" as any,
        options: [
          { id: "nowrap", label: "Nowrap" },
          { id: "wrap", label: "Wrap" },
          { id: "wrap-reverse", label: "Wrap-reverse" },
        ],
      },
      {
        name: "Justify content",
        property: "justify-content",
        type: "select" as any,
        options: [
          { id: "flex-start", label: "Début" },
          { id: "center", label: "Centre" },
          { id: "flex-end", label: "Fin" },
          { id: "space-between", label: "Space-between" },
          { id: "space-around", label: "Space-around" },
          { id: "space-evenly", label: "Space-evenly" },
        ],
      },
      {
        name: "Align items",
        property: "align-items",
        type: "select" as any,
        options: [
          { id: "stretch", label: "Stretch" },
          { id: "flex-start", label: "Début" },
          { id: "center", label: "Centre" },
          { id: "flex-end", label: "Fin" },
          { id: "baseline", label: "Baseline" },
        ],
      },
      {
        name: "Align self",
        property: "align-self",
        type: "select" as any,
        options: [
          { id: "auto", label: "Auto" },
          { id: "stretch", label: "Stretch" },
          { id: "flex-start", label: "Début" },
          { id: "center", label: "Centre" },
          { id: "flex-end", label: "Fin" },
        ],
      },
      {
        name: "Gap",
        property: "gap",
        type: "integer" as any,
        units: ["px", "%", "em", "rem"],
        unit: "px",
        min: 0,
        max: 200,
      },
      {
        name: "Flex grow",
        property: "flex-grow",
        type: "integer" as any,
        units: [""],
        unit: "",
        min: 0,
        max: 10,
      },
      {
        name: "Flex shrink",
        property: "flex-shrink",
        type: "integer" as any,
        units: [""],
        unit: "",
        min: 0,
        max: 10,
      },
      {
        name: "Flex basis",
        property: "flex-basis",
        type: "integer" as any,
        units: ["px", "%", "em", "auto"],
        unit: "px",
        min: 0,
        max: 5000,
      },
      {
        name: "Grid colonnes",
        property: "grid-template-columns",
        type: "base" as any,
      },
      {
        name: "Grid lignes",
        property: "grid-template-rows",
        type: "base" as any,
      },
    ],
  },
  {
    id: "effects",
    name: "Effets",
    open: false,
    properties: [
      {
        name: "Opacité",
        property: "opacity",
        type: "slider" as any,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        name: "Ombre boîte",
        property: "box-shadow",
        type: "base" as any,
      },
      {
        name: "Filtre",
        property: "filter",
        type: "base" as any,
      },
      {
        name: "Backdrop filter",
        property: "backdrop-filter",
        type: "base" as any,
      },
      {
        name: "Blend mode",
        property: "mix-blend-mode",
        type: "select" as any,
        options: [
          { id: "normal", label: "Normal" },
          { id: "multiply", label: "Multiply" },
          { id: "screen", label: "Screen" },
          { id: "overlay", label: "Overlay" },
          { id: "darken", label: "Darken" },
          { id: "lighten", label: "Lighten" },
        ],
      },
    ],
  },
  {
    id: "transform",
    name: "Transformation",
    open: false,
    properties: [
      { name: "Transform", property: "transform", type: "base" as any },
      { name: "Transition", property: "transition", type: "base" as any },
      {
        name: "Curseur",
        property: "cursor",
        type: "select" as any,
        options: [
          { id: "default", label: "Default" },
          { id: "pointer", label: "Pointer" },
          { id: "move", label: "Move" },
          { id: "text", label: "Text" },
          { id: "not-allowed", label: "Not-allowed" },
          { id: "grab", label: "Grab" },
        ],
      },
      {
        name: "Object fit",
        property: "object-fit",
        type: "select" as any,
        options: [
          { id: "fill", label: "Fill" },
          { id: "contain", label: "Contain" },
          { id: "cover", label: "Cover" },
          { id: "none", label: "None" },
          { id: "scale-down", label: "Scale-down" },
        ],
      },
    ],
  },
];
